import Image from "next/image";
import Jumbotron from "./Components/Jumbotron";
import Description from "./Components/Description";
import type { Metadata } from "next";
import { getAllArtistsWithFeaturedProjects } from "@/strapi/strapi-utils";
import { NewMusic } from "./Components/NewMusic";
import FeaturedArtists from "./Components/FeaturedArtists";
import { Artist } from "@/types/Artist";
import { PageWrapper } from "./Components/PageWrapper";

export const metadata: Metadata = {
  title: "Good Natured Souls",
  description: "Generated by create next app",
};

export default async function Home() {
  const homePageData = await getAllArtistsWithFeaturedProjects();
  return (
    <main>
      <PageWrapper>
        <Jumbotron />
        <Description />
        <NewMusic projects={homePageData.featuredProjects} />
        <FeaturedArtists artists={homePageData.artists} />
      </PageWrapper>
    </main>
  );
}
